[package]
name = "chip8-emulator"
version = "0.1.0"
edition = "2021"
authors = ["Tyson Liddell <tysonliddell@hotmail.com>"]
description = "A CHIP-8 emulator"

[dependencies]
clap = { version = "4.1.13", features = ["derive"] }
